name: sahabat_tugas
description: A new Flutter project.

publish_to: "none" # Hapus baris ini jika Anda ingin mempublikasikannya

version: 1.0.0+1

environment:
  sdk: ">=2.18.6 <3.0.0"

dependencies:
  cloud_firestore: ^5.1.0
  concentric_transition: ^1.0.3
  cupertino_icons: ^1.0.2
  firebase_auth: ^5.1.2
  firebase_core: ^3.2.0
  flutter:
    sdk: flutter
  gradle_properties: ^1.0.2
  intl: ^0.19.0
  salomon_bottom_bar: ^3.3.1

dev_dependencies:
  flutter_lints: ^2.0.0
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true

  assets:
    - assets/icon/icon.jpg
    - assets/icon/icons.png
